FROM node:20-alpine AS build

WORKDIR /app/web

COPY web/package.json web/pnpm-lock.yaml ./
RUN corepack enable && pnpm install --frozen-lockfile

COPY web ./
RUN pnpm build


FROM node:20-alpine AS runtime

WORKDIR /app/web

ENV NODE_ENV=production \
    PORT=3000 \
    HOSTNAME=0.0.0.0

RUN corepack enable

COPY --from=build /app/web/.next ./.next
COPY --from=build /app/web/package.json ./package.json
COPY --from=build /app/web/pnpm-lock.yaml ./pnpm-lock.yaml
COPY --from=build /app/web/node_modules ./node_modules
COPY --from=build /app/web/next.config.mjs ./next.config.mjs
COPY --from=build /app/web/postcss.config.js ./postcss.config.js
COPY --from=build /app/web/tailwind.config.ts ./tailwind.config.ts
COPY --from=build /app/web/schema ./schema

EXPOSE 3000

CMD ["pnpm", "start", "-p", "3000", "-H", "0.0.0.0"]
